### ISSUE TITLE
[feature] Support Model Conversion/Compression via CRD

### ISSUE THREAD

**Issue by gaocegege** [caicloud/ormb#23]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature

**What happened**:

We should support model conversion and compression. We can have a init container to pull the model from registry to local filesystem. Then we can use MMdnn or other tools to convert/compress the model, then we can push the new model with the unique tag or the desired tag.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

https://github.com/gaocegege/ormb/tree/modeljob

**Comment by gaocegege** [comment]
BTW, we can use Harbor Webhooks to trigger model analyzer: https://goharbor.io/docs/2.0.0/working-with-projects/project-configuration/configure-webhooks/

**Comment by gaocegege** [comment]
/assign @simon-cj 

@simon-cj currently has the bandwidth for it.

**Comment by ddysher** [comment]
what's the status? @simon-cj 

Can we have a WIP or design doc first?  (e.g. I want to know why do we need CRD for this...)

**Comment by gaocegege** [comment]
The CRD is to avoid self-maintained queue in the implementation.https://docs.google.com/document/d/1JyjCzpO0NrsIOK29i_b2vTPpYc6-ckNcCVquOCj2ooM/edit?ts=5ec22fe9#heading=h.6j6pdsfmko7y

**Comment by simon-cj** [comment]
CRD design doc is provided by gaocegege， recently， I‘am updating extrat and
convert python script and verify logic by ormb. so， the crd controller is
simple now, I will complete next.

**Comment by ddysher** [comment]
IIUC, the CRD design should be part of model-registry, not part of ormb. Are we going to create a new repository or work in ormb directly but create a new component?
> The CRD is to avoid self-maintained queue in the implementation.https://docs.google.com/document/d/1JyjCzpO0NrsIOK29i_b2vTPpYc6-ckNcCVquOCj2ooM/edit?ts=5ec22fe9#heading=h.6j6pdsfmko7y

**Comment by gaocegege** [comment]
Depends on the scope of ormb. We can discuss it on the meeting.

**Comment by simon-cj** [comment]
for "the CRD design should be part of model-registry“, emmm, SGTM.

the second question need to discuss， @高策 <gaoce@caicloud.io> suggest work
in ormb directly last time.

**Comment by ddysher** [comment]
LGTM

@simon-cj you are mixing Half-width & Full-width punctuation marks :)
> CRD design doc is provided by gaocegege， recently， I‘am updating extrat and
convert python script and verify logic by ormb. so， the crd controller is
simple now, I will complete next.

**Comment by gaocegege** [comment]
Ref https://github.com/caicloud/temp-model-registry/
