### ISSUE TITLE
[feature] Dashboard UI for ormb

### ISSUE THREAD

**Issue by gaocegege** [caicloud/ormb#24]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature

**What happened**:

ORMB is a CLI to manage your ML models. We need a dashbaord like Harbor Portal to show the model list and the artifact details for one given model.

Besides this, we need to support creating model inference services in the UI. Maybe we should get in touch with Seldon Core community.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by gaocegege** [comment]
UI is blocked by #12

**Comment by ddysher** [comment]
should this be part of ormb or model-registry?

**Comment by gaocegege** [comment]
part of model-registry.

**Comment by gaocegege** [comment]
It does not block the UI anymore since we have a patch here gaocegege/harbor@da3d92c to support model in our fork.

**Comment by gaocegege** [comment]
We prefer not to place model and inference mixed in UI, since model is like Docker images, and model inference is like microservices. We do not support microservices in Harbor UI, then I think we should not keep inference in model registry UI

**Comment by gaocegege** [comment]
The UI will be in https://github.com/caicloud/temp-model-registry/ , thus I am going to close the issue.
