### ISSUE TITLE
[upstream contribution] Support ormb in Seldon Core and KFServing

### ISSUE THREAD

**Issue by gaocegege** [caicloud/ormb#25]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature

**What happened**:

ormb should be able to be used in KFServing and Seldon Core to pull/push models.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by gaocegege** [comment]
https://docs.seldon.io/projects/seldon-core/en/v1.1.0/developer/community.html

**Comment by gaocegege** [comment]
Seldon Core already supports multiple storage backend here github.com/SeldonIO/seldon-core/python/seldon_core/storage.py, thus it should not be hard to support ormb.

Doc is here https://docs.seldon.io/projects/seldon-core/en/v1.1.0/reference/release-0.4.0.html?highlight=s3#prepackaged-model-servers

**Comment by ddysher** [comment]
Is there any upstream tracking issue?

**Comment by gaocegege** [comment]
No, going to request a demo show slot in seldon core community call. Now do not have the bandwidth for it currently. I think we should have a blog post in English for it first, then the community members can know more about our project.

**Comment by ddysher** [comment]
ok, SGTM

**Comment by gaocegege** [comment]
We decide to implement it in our fork first to provide the end-to-end prototype.

**Comment by gaocegege** [comment]
Ref #34 

KFServing and Seldon Core download the model using Python code. Now we will implement our own initializer using Golang.

**Comment by gaocegege** [comment]
We have to fork the seldon-core to support auth for ormb. Ref https://github.com/gaocegege/seldon-core/pull/2

**Comment by gaocegege** [comment]
Now we succeed to run Seldcon Core deployment with ormb in gaocegege/seldon-core#2 . But we have some modifications for it. Maybe we should try to:

- Investigate if we can use the config here to replace aws with ormb https://github.com/gaocegege/seldon-core/blob/ormb/operator/config/manager/configmap.yaml#L14

**Comment by gaocegege** [comment]
We do not need to modify seldon core code. Things we need to do for the issue is to present it in Seldon Core community.

**Comment by gaocegege** [comment]
ref #44
