### ISSUE TITLE
[enhancement] Design v1 Model Config Specification

### ISSUE THREAD

**Issue by gaocegege** [caicloud/ormb#3]
We should define the specification for mediaType `application/vnd.caicloud.model.config.v1+json`. 

We can refer to https://github.com/opencontainers/image-spec/blob/master/config.md

/priority p0

**Comment by ddysher** [comment]
These designs/discussions might be useful as well:
- https://github.com/operator-framework/operator-registry/blob/master/docs/design/operator-bundle.md
- https://github.com/operator-framework/enhancements/tree/master/enhancements
- https://github.com/kubernetes/enhancements/pull/1481

**Comment by ddysher** [comment]
There are discussion about merging such addon bundle in a unified structure, but I don't think it will come any time soom.

**Comment by gaocegege** [comment]
Yeah, I think CNAB and Docker Image specification is helpful for us currently.
