### ISSUE TITLE
[feature] Support hook when pushing models

### ISSUE THREAD

**Issue by codeflitting** [caicloud/ormb#33]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind feature

For automatically update the model service, the command line tool should support hooks

/cc @gaocegege @ddysher

**Comment by gaocegege** [comment]
SGTM. There are several ways to do:

- Use Harbor webhook https://goharbor.io/docs/2.0.0/working-with-projects/project-configuration/configure-webhooks/
- Implement the model-registry backend and act as the proxy to Harbor. Add the hook logic in the model-registry layer.

**Comment by gaocegege** [comment]
We are going to follow the second approach. The feature will be implemented in https://github.com/caicloud/temp-model-registry

/close

/cc @simon-cj
