### ISSUE TITLE
[feature] Provide Python SDK

### ISSUE THREAD

**Issue by gaocegege** [caicloud/ormb#34]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature

**What happened**:

We need to provide Python SDK like https://docker-py.readthedocs.io/en/stable/ to support CURD in Jupyter Notebook or Python code directly.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by ddysher** [comment]
If OCI registry supports artifact like container image, then i'd expect we can use some industrial standard to interact with OCI registry?

**Comment by gaocegege** [comment]
theoretically yes.

**Comment by gaocegege** [comment]
Welcome @ZhuYuJin

Thanks for your interest for the issue. We can keep sync here.

**Comment by gaocegege** [comment]
Ref https://github.com/deislabs/oras/issues/166
