### ISSUE TITLE
[chore] Enable Travis CI for the repository

### ISSUE THREAD

**Issue by gaocegege** [caicloud/ormb#59]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind feature

**What happened**:

We need the Travis CI to CI/CD the project.

/cc @pendoragon @ddysher 

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by ddysher** [comment]
Added the repository in Travis, build status logo can be found at https://travis-ci.org/caicloud/ormb.svg?branch=master
