### ISSUE TITLE
[discussion] Design signature field carefully

### ISSUE THREAD

**Issue by gaocegege** [caicloud/ormb#62]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature

**What happened**:

We need to design signature carefully to support existing features.

/cc @simon-cj Can you show your ideas here?

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by simon-cj** [comment]
ok, I need to tidy up, I will comment here when complete

**Comment by simon-cj** [comment]
there are the following problems:
- Do we need to uniform field？ eg： in our clever product， Tensor include `name，dims， dataType`, correspond to `name, size, dtype`  in ormb spec.
- for PMML, need to add some extra field, eg: `opType, values`.  the following code is PMML's input example:
   `"inputFields" : [ {
      "id" : "displ",
      "dataType" : "double",
      "opType" : "continuous",
      "values" : [ "[1.6, 7.0]" ]
    }, {
      "id" : "year",
      "dataType" : "double",
      "opType" : "continuous",
      "values" : [ "[1999.0, 2008.0]" ]
    }, {
      "id" : "cyl",
      "dataType" : "double",
      "opType" : "continuous",
      "values" : [ "[4.0, 8.0]" ]
    }, {
      "id" : "class",
      "dataType" : "string",
      "opType" : "categorical",
      "values" : [ "2seater", "compact", "midsize", "minivan", "pickup", "subcompact", "suv" ]
    } ]`

**Comment by gaocegege** [comment]
For PMML, should we still use Tensor here? I think it is not actually a Tensor.

**Comment by simon-cj** [comment]
yes, For PMML, it is not a Tensor, maybe need to definition a special struct, but priority is low

**Comment by gaocegege** [comment]
SGTM. Can you open the PR then let's review the corresponding changes there?

**Comment by simon-cj** [comment]
OK, I will do it

**Comment by gaocegege** [comment]
/close

I am closing it since it is merged #72
