### ISSUE TITLE
[enhancemnt] Customize the path of OCIStore cache and config.json

### ISSUE THREAD

**Issue by gaocegege** [caicloud/ormb#9]
OCIStore cache and config.json are used by ormb to store login information and layers for models. Now it is initialized in the current directory, we should use a home-based path (Maybe `$HOME/.cache/ormb/`) by default and support customization.

**Comment by ddysher** [comment]
we can just leverage XDG?

https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by gaocegege** [comment]
Will have a look.

**Comment by gaocegege** [comment]
Closed by #17
